require('dotenv').config()
const express=require('express')
const cors=require('cors')
const port=3009
const app=express()
app.use(express.json())
const { checkSchema, check } = require('express-validator')
app.use(cors())
const configDb=require('./config/db')
configDb()
const {authenticateUser}=require('./app/middlewares/auth')
const usersCntrl=require('./app/controller/users-controller')
const {usersValidation,loginValidation}=require('./app/validation/users-validation')
const noteCntrl = require('./app/controller/note-controoler')
const {noteValidation,noteUpdateValidation}=require('./app/validation/note-validation')
app.post('/api/register',checkSchema(usersValidation),usersCntrl.register)
app.post('/api/login',checkSchema(loginValidation),usersCntrl.login)
app.get('/api/note',authenticateUser,noteCntrl.myNote)
app.get('/api/account',authenticateUser,usersCntrl.myaccount)
app.post('/api/create/note', authenticateUser,checkSchema(noteValidation),noteCntrl.create)
app.put('/api/update/note/:id',authenticateUser,checkSchema(noteUpdateValidation),noteCntrl.update)
app.delete('/api/note/delete/:id',authenticateUser,noteCntrl.remove)
app.post('/api/note/share/:id',authenticateUser,noteCntrl.share)
app.get('/api/users',authenticateUser,usersCntrl.users)
app.listen(port,()=>{
    console.log("server is running in port" + port)
})